environment:
  LIBELF_INSTALL_PREFIX: "C:/libelf"
  matrix:
    - platform: Win32
      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015"
    - platform: x64
      CMAKE_GENERATOR_NAME: "Visual Studio 14 2015 Win64"
  
configuration: Release

install:
  - git clone https://github.com/dvirtz/libelf.git
  - cd libelf
  - git checkout cmake
  - cmake . -B_build -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_INSTALL_PREFIX=%LIBELF_INSTALL_PREFIX%
  - cmake --build _build --config %CONFIGURATION%
  - cmake --build _build --config %CONFIGURATION% --target INSTALL
  - cd ..

build_script:
  - cmake . -B_build -G "%CMAKE_GENERATOR_NAME%" -DLIBELF_ROOT=%LIBELF_INSTALL_PREFIX%
  - cmake --build _build --config %CONFIGURATION%
  
test_script:
  - cmake --build _build --config %CONFIGURATION% --target RUN_TESTS
  